disabled_rules:
- trailing_whitespace
- force_cast
- private_over_fileprivate
- force_try
- empty_enum_arguments
- class_delegate_protocol
- identifier_name
- line_length
- nesting
- unused_setter_value
- file_length
- for_where
- type_body_length
- weak_delegate
- type_name
- opening_brace
- redundant_optional_initialization
- unused_optional_binding
- colon
- vertical_whitespace
- trailing_newline
- function_body_length
- cyclomatic_complexity
- operator_whitespace
- closure_parameter_position
- trailing_comma
- vertical_parameter_alignment
- void_return
- syntactic_sugar
- mark
- unused_closure_parameter
- redundant_discardable_let
- unneeded_break_in_switch
- comma
- control_statement
- redundant_objc_attribute
- function_parameter_count
- statement_position
- return_arrow_whitespace
- multiple_closures_with_trailing_closure
- redundant_void_return
- todo
